---
- name: Create manifest directory
  file:
    path: /playbooks/manifests
    state: directory
    mode: '0755'
- name: Template a Secret with cloud credentials
  ansible.builtin.template:
    src: "../templates/credentials.yml.j2"
    dest: "/playbooks/manifests/{{ ansible_facts['aws_domain'] }}-credentials.yml"
    mode: '0600'
