---
- name: Template a Secret with cloud credentials
  ansible.builtin.template:
    src: "{{ lookup('template', 'credentials.yml.j2') }}"
    dest: "{{ ansible_facts['aws_domain'] }}-credentials.yml"
    mode: '0600'
